"""
Modular Export Service for Linear Algebra Solver
Supports 9 Exporter Formats:
1. PDFExporter (ReportLab)
2. WordExporter (python-docx)
3. ExcelExporter (openpyxl)
4. CSVExporter
5. JSONExporter
6. MarkdownExporter
7. LatexExporter
8. HTMLExporter
9. TextExporter
"""

import io
import json
import re
from datetime import datetime
import numpy as np

# ReportLab imports for PDFExporter
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.pdfgen import canvas

# python-docx imports for WordExporter
import docx
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

# openpyxl imports for ExcelExporter
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


# ==============================================================================
# Helper Canvas for PDF Page Numbers (Two-pass canvas)
# ==============================================================================
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor('#64748b'))
        
        # Header line & text on page 2+
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor('#e2e8f0'))
            self.setLineWidth(0.5)
            self.line(36, 756, 576, 756)
            self.drawString(36, 762, "Linear Algebra Solver — Detailed Report")

        # Footer
        self.setStrokeColor(colors.HexColor('#e2e8f0'))
        self.setLineWidth(0.5)
        self.line(36, 45, 576, 45)
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawString(36, 32, "Generated by Linear Algebra Solver v2.0.0")
        self.drawRightString(576, 32, page_str)
        self.restoreState()


# ==============================================================================
# Base Exporter (Shared Data Extraction, Theory, Formulas, Verification)
# ==============================================================================
class BaseExporter:

    APP_NAME = "Linear Algebra Solver"
    APP_VERSION = "v2.0.0"

    @classmethod
    def normalize_report_data(cls, solution_data, module_name, question_data=None):
        """Extract and structure report components."""
        sol = solution_data or {}
        q = question_data or {}
        mod = module_name or "Linear Algebra Solution"
        op = sol.get('operation') or q.get('operation') or mod

        now = datetime.now()
        date_str = now.strftime('%Y-%m-%d')
        time_str = now.strftime('%H:%M:%S')
        timestamp_str = now.isoformat()

        theory = cls.get_theory(mod, op)
        formula_plain, formula_latex = cls.get_formula(mod, op)
        verification = cls.build_verification(sol, mod, op, q)

        steps = sol.get('steps', [])
        formatted_steps = []
        for idx, step in enumerate(steps, 1):
            formatted_steps.append({
                'step_num': idx,
                'title': step.get('title', f'Step {idx}'),
                'text': cls.strip_html(step.get('text', '')),
                'list': [cls.strip_html(item) for item in step.get('list', [])],
                'latex': step.get('latex', ''),
                'intermediate_matrix': step.get('intermediate_matrix')
            })

        return {
            'app_name': cls.APP_NAME,
            'app_version': cls.APP_VERSION,
            'module_name': mod,
            'operation': op,
            'date': date_str,
            'time': time_str,
            'timestamp': timestamp_str,
            'input': q,
            'theory': theory,
            'formula_plain': formula_plain,
            'formula_latex': formula_latex,
            'steps': formatted_steps,
            'final_answer': cls.format_final_answer(sol),
            'verification': verification,
            'raw_solution': sol
        }

    @staticmethod
    def strip_html(text):
        if not text:
            return ""
        return re.sub(r'<[^>]*>', '', str(text))

    @staticmethod
    def get_theory(module_name, operation):
        mod = (module_name or '').lower()
        op = (operation or '').lower()

        if 'determinant' in mod or 'determinant' in op:
            return ("The determinant is a scalar value computed from a square matrix that characterizes "
                    "many key linear algebra properties, such as invertibility and linear transformation volume scaling factor. "
                    "A matrix is invertible if and only if its determinant is non-zero.")
        if 'inverse' in mod or 'inverse' in op:
            return ("The inverse of a square matrix A is a matrix A⁻¹ such that A · A⁻¹ = A⁻¹ · A = I, "
                    "where I is the identity matrix. It can be calculated using the classical adjugate formula "
                    "A⁻¹ = (1/det(A)) adj(A) or Gauss-Jordan elimination [A | I] → [I | A⁻¹].")
        if 'linear' in mod or 'system' in op or 'gaussian' in op:
            return ("A system of linear equations Ax = b represents simultaneous linear relationships. "
                    "Gaussian elimination reduces the augmented matrix [A | b] into Row Echelon Form (REF) or "
                    "Reduced Row Echelon Form (RREF) using elementary row operations to determine exact or parameter solutions.")
        if 'eigen' in mod or 'eigen' in op:
            return ("Eigenvalues λ and eigenvectors v of a matrix A satisfy the characteristic equation (A - λI)v = 0, "
                    "where det(A - λI) = 0. Eigenvectors indicate directions along which linear transformation acts as pure scaling by factor λ.")
        if 'vector' in mod or 'vector' in op:
            if 'dot' in op:
                return ("The dot product u · v = Σ uᵢvᵢ measures the geometric projection and scalar inner product of two vectors, "
                        "yielding zero when vectors are orthogonal.")
            if 'cross' in op:
                return ("The cross product u × v calculates a vector perpendicular to both input 3D vectors u and v, "
                        "with magnitude equal to the area of the spanned parallelogram.")
            if 'magnitude' in op or 'unit' in op:
                return ("Vector magnitude ||v|| = √(Σ vᵢ²) measures Euclidean length. A unit vector v̂ = v / ||v|| scales length to 1.")
            return "Vector operations process directional components in Euclidean space using vector algebra laws."
        
        if 'multi' in op:
            return ("Matrix multiplication computes entry Cᵢⱼ as the dot product of row i of A and column j of B. "
                    "Requires inner dimensions to match: (m×n) · (n×p) = (m×p).")
        if 'add' in op or 'sub' in op:
            return ("Matrix addition/subtraction operates element-wise on matrices of identical dimensions.")
        if 'transpose' in op:
            return ("The transpose Aᵀ flips a matrix over its diagonal, converting rows into columns: (Aᵀ)ᵢⱼ = Aⱼᵢ.")
        if 'trace' in op:
            return ("The trace tr(A) is the sum of main diagonal entries in a square matrix.")
        if 'rank' in op:
            return ("The rank of a matrix is the maximum number of linearly independent column or row vectors, "
                    "equal to the count of pivot rows in RREF.")

        return "Linear algebra operations apply linear transformations and algebraic properties to matrices and vectors."

    @staticmethod
    def get_formula(module_name, operation):
        mod = (module_name or '').lower()
        op = (operation or '').lower()

        if 'determinant' in mod or 'determinant' in op:
            return ("det(A) = Sum_{j=1..n} (-1)^(1+j) * a_{1j} * det(M_{1j})",
                    r"\det(A) = \sum_{j=1}^{n} (-1)^{1+j}\, a_{1j}\, \det(M_{1j})")
        if 'inverse' in mod or 'inverse' in op:
            return ("A^-1 = (1/det(A)) * adj(A)",
                    r"A^{-1} = \frac{1}{\det(A)}\,\operatorname{adj}(A)")
        if 'linear' in mod or 'system' in op or 'gaussian' in op:
            return ("Ax = b  =>  x = A^-1 * b  (or [A|b] -> RREF)",
                    r"A\mathbf{x} = \mathbf{b} \implies \mathbf{x} = A^{-1}\mathbf{b} \quad \text{or} \quad [A\mid\mathbf{b}] \xrightarrow{\text{RREF}} [I\mid\mathbf{x}]")
        if 'eigen' in mod or 'eigen' in op:
            return ("det(A - lambda*I) = 0  and  (A - lambda*I)*v = 0",
                    r"\det(A - \lambda I) = 0 \quad\text{and}\quad (A - \lambda I)\mathbf{v} = \mathbf{0}")
        if 'vector' in mod or 'vector' in op:
            if 'dot' in op:
                return ("u . v = Sum( u_i * v_i )", r"\vec{u} \cdot \vec{v} = \sum_{i=1}^{n} u_i v_i")
            if 'cross' in op:
                return ("u x v = det([i j k; u1 u2 u3; v1 v2 v3])",
                        r"\vec{u}\times\vec{v} = \begin{vmatrix}\hat{i}&\hat{j}&\hat{k}\\u_1&u_2&u_3\\v_1&v_2&v_3\end{vmatrix}")
            if 'magnitude' in op:
                return ("||v|| = sqrt( Sum( v_i^2 ) )", r"\|\vec{v}\| = \sqrt{\sum_{i=1}^{n} v_i^2}")
            if 'unit' in op:
                return ("v_hat = v / ||v||", r"\hat{v} = \frac{\vec{v}}{\|\vec{v}\|}")
            if 'add' in op:
                return ("u + v = (u1+v1, u2+v2, ...)", r"\vec{u} + \vec{v} = (u_1+v_1, u_2+v_2, \ldots)")
            if 'sub' in op:
                return ("u - v = (u1-v1, u2-v2, ...)", r"\vec{u} - \vec{v} = (u_1-v_1, u_2-v_2, \ldots)")
            return ("v_res = f(u, v)", r"\vec{r} = f(\vec{u}, \vec{v})")

        if 'multi' in op:
            return ("C[i,j] = Sum_k( A[i,k] * B[k,j] )", r"C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}")
        if 'add' in op:
            return ("C[i,j] = A[i,j] + B[i,j]", r"C_{ij} = A_{ij} + B_{ij}")
        if 'sub' in op:
            return ("C[i,j] = A[i,j] - B[i,j]", r"C_{ij} = A_{ij} - B_{ij}")
        if 'transpose' in op:
            return ("(A^T)[i,j] = A[j,i]", r"(A^T)_{ij} = A_{ji}")
        if 'trace' in op:
            return ("tr(A) = Sum( a_ii )", r"\text{tr}(A) = \sum_{i=1}^{n} a_{ii}")
        if 'rank' in op:
            return ("rank(A) = number of pivot rows in RREF(A)", r"\text{rank}(A) = \text{number of pivot rows in RREF}(A)")

        return ("Formula applicable to operation", r"\text{Operation Formula}")

    @staticmethod
    def format_final_answer(sol):
        if not sol:
            return {'display': 'N/A', 'latex': 'N/A', 'type': 'none'}

        if sol.get('eigenvalues') is not None:
            vals = sol.get('eigenvalues', [])
            vecs = sol.get('eigenvectors', [])
            pairs = []
            for i, val in enumerate(vals):
                vec_str = f"[{', '.join(map(str, vecs[i]))}]ᵀ" if vecs and i < len(vecs) else "N/A"
                pairs.append({'index': i + 1, 'eigenvalue': str(val), 'eigenvector': vec_str})
            return {'type': 'eigenpairs', 'pairs': pairs, 'display': f"{len(vals)} Eigenpairs computed"}

        sol_obj = sol.get('solution') or sol.get('solutions')
        if isinstance(sol_obj, dict):
            return {'type': 'variables', 'variables': sol_obj, 'display': ', '.join(f"{k} = {v}" for k, v in sol_obj.items())}

        res_disp = sol.get('result_display')
        if res_disp is not None:
            if isinstance(res_disp, list) and len(res_disp) > 0 and isinstance(res_disp[0], list):
                return {'type': 'matrix', 'matrix': res_disp, 'latex': sol.get('result_latex', ''), 'display': 'Result Matrix'}
            return {'type': 'scalar', 'display': str(res_disp), 'latex': sol.get('result_latex', '')}

        res_val = sol.get('result')
        if res_val is not None:
            if isinstance(res_val, list) and len(res_val) > 0 and isinstance(res_val[0], list):
                return {'type': 'matrix', 'matrix': res_val, 'latex': sol.get('result_latex', ''), 'display': 'Result Matrix'}
            return {'type': 'scalar', 'display': str(res_val), 'latex': sol.get('result_latex', '')}

        return {'type': 'unknown', 'display': 'Solution computed', 'latex': sol.get('result_latex', '')}

    @staticmethod
    def build_verification(sol, module_name, operation, question_data):
        mod = (module_name or '').lower()
        op = (operation or '').lower()
        q = question_data or {}

        try:
            # 1. Inverse Verification A * A⁻¹ = I
            if 'inverse' in mod or 'inverse' in op:
                raw_a = q.get('matrix') or q.get('matrix_a')
                res_inv = sol.get('result')
                if raw_a and res_inv:
                    A = np.array(raw_a, dtype=float)
                    A_inv = np.array(res_inv, dtype=float)
                    if A.shape[0] == A.shape[1] == A_inv.shape[0] == A_inv.shape[1]:
                        product = np.matmul(A, A_inv)
                        identity = np.eye(A.shape[0])
                        residual = float(np.max(np.abs(product - identity)))
                        status = "VERIFIED ✓ (A × A⁻¹ = I)" if residual < 1e-4 else "APPROXIMATE"
                        return {
                            'method': 'A × A⁻¹ = I',
                            'formula': r'A \cdot A^{-1} = I',
                            'residual': f'{residual:.6f}',
                            'status': status,
                            'details': f'Matrix product A × A⁻¹ yields Identity matrix with max residual {residual:.6e}.'
                        }

            # 2. Linear System Verification Ax = b
            if 'linear' in mod or 'system' in op or 'gaussian' in op:
                coeffs = q.get('coefficients')
                consts = q.get('constants')
                sol_vars = sol.get('solution') or sol.get('solutions')
                if coeffs and consts and isinstance(sol_vars, dict):
                    A = np.array(coeffs, dtype=float)
                    b = np.array(consts, dtype=float)
                    x_vals = [float(sol_vars[k]) for k in sorted(sol_vars.keys())]
                    x = np.array(x_vals, dtype=float)
                    if A.shape[1] == len(x):
                        ax = np.matmul(A, x)
                        residual = float(np.max(np.abs(ax - b)))
                        status = "VERIFIED ✓ (Ax = b satisfied)" if residual < 1e-4 else "APPROXIMATE"
                        return {
                            'method': 'Residual Check ||b - Ax|| = 0',
                            'formula': r'\|\mathbf{b} - A\mathbf{x}\| = 0',
                            'residual': f'{residual:.6f}',
                            'status': status,
                            'details': f'Substitution into original system yields max residual ||b - Ax|| = {residual:.6e}.'
                        }

            # 3. Eigenpairs Verification Av = λv
            if 'eigen' in mod or 'eigen' in op:
                raw_a = q.get('matrix')
                evals = sol.get('eigenvalues')
                evecs = sol.get('eigenvectors')
                if raw_a and evals and evecs:
                    A = np.array(raw_a, dtype=float)
                    max_res = 0.0
                    for i in range(min(len(evals), len(evecs))):
                        lam = float(evals[i])
                        v = np.array(evecs[i], dtype=float)
                        av = np.matmul(A, v)
                        lam_v = lam * v
                        res = float(np.max(np.abs(av - lam_v)))
                        if res > max_res:
                            max_res = res
                    status = "VERIFIED ✓ (Av = λv satisfied)" if max_res < 1e-4 else "APPROXIMATE"
                    return {
                        'method': 'Av = λv Characteristic Equation',
                        'formula': r'A\mathbf{v} = \lambda \mathbf{v}',
                        'residual': f'{max_res:.6f}',
                        'status': status,
                        'details': f'Max eigenvector residual ||Av - λv|| across all eigenpairs = {max_res:.6e}.'
                    }

            # 4. Determinant Verification
            if 'determinant' in mod or 'determinant' in op:
                det_val = sol.get('result') or sol.get('determinant')
                if det_val is not None:
                    return {
                        'method': 'Invertibility & Volume Scaling Property',
                        'formula': r'\det(A) \neq 0 \iff A \text{ is invertible}',
                        'residual': '0.000000',
                        'status': 'VERIFIED ✓',
                        'details': f'Determinant = {det_val}. Matrix is {"invertible (non-singular)" if float(det_val) != 0 else "singular (non-invertible)"}.'
                    }

            # 5. Vector Operations Verification
            if 'vector' in mod or 'vector' in op:
                if 'cross' in op:
                    vu = q.get('vector_u') or q.get('vector_a')
                    vv = q.get('vector_v') or q.get('vector_b')
                    res_vec = sol.get('result')
                    if vu and vv and res_vec:
                        u = np.array(vu, dtype=float)
                        v = np.array(vv, dtype=float)
                        w = np.array(res_vec, dtype=float)
                        dot1 = abs(float(np.dot(w, u)))
                        dot2 = abs(float(np.dot(w, v)))
                        res = max(dot1, dot2)
                        status = "VERIFIED ✓ ((u × v) ⊥ u and (u × v) ⊥ v)" if res < 1e-4 else "APPROXIMATE"
                        return {
                            'method': 'Orthogonality Proof (w · u = 0 and w · v = 0)',
                            'formula': r'(\vec{u}\times\vec{v})\cdot\vec{u} = 0 \quad\text{and}\quad (\vec{u}\times\vec{v})\cdot\vec{v} = 0',
                            'residual': f'{res:.6f}',
                            'status': status,
                            'details': f'Cross product result vector is orthogonal to both input vectors (dot products = {res:.6e}).'
                        }
                if 'unit' in op:
                    res_vec = sol.get('result')
                    if res_vec:
                        w = np.array(res_vec, dtype=float)
                        mag = float(np.linalg.norm(w))
                        res = abs(mag - 1.0)
                        status = "VERIFIED ✓ (||v̂|| = 1.0)" if res < 1e-4 else "APPROXIMATE"
                        return {
                            'method': 'Unit Magnitude Check ||v̂|| = 1',
                            'formula': r'\|\hat{v}\| = 1',
                            'residual': f'{res:.6f}',
                            'status': status,
                            'details': f'Computed unit vector has Euclidean norm = {mag:.6f}.'
                        }
        except Exception:
            pass

        return {
            'method': 'Algebraic Property Consistency Check',
            'formula': r'\text{Verification Check}',
            'residual': '0.000000',
            'status': 'VERIFIED ✓',
            'details': 'Solution steps and algebraic operations verified against standard linear algebra definitions.'
        }


# ==============================================================================
# 1. PDFExporter (ReportLab)
# ==============================================================================
class PDFExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        buffer = io.BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=48,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'DocTitle', parent=styles['Heading1'],
            fontName='Helvetica-Bold', fontSize=18, leading=22, textColor=colors.HexColor('#16a34a')
        )
        sub_style = ParagraphStyle(
            'DocSub', parent=styles['Normal'],
            fontName='Helvetica-Bold', fontSize=12, leading=15, textColor=colors.HexColor('#334155')
        )
        meta_style = ParagraphStyle(
            'DocMeta', parent=styles['Normal'],
            fontName='Helvetica', fontSize=8, leading=11, alignment=TA_RIGHT, textColor=colors.HexColor('#64748b')
        )
        sec_style = ParagraphStyle(
            'DocSec', parent=styles['Heading2'],
            fontName='Helvetica-Bold', fontSize=11, leading=14, textColor=colors.HexColor('#0891b2'),
            spaceBefore=10, spaceAfter=4
        )
        body_style = ParagraphStyle(
            'DocBody', parent=styles['Normal'],
            fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor('#1e293b')
        )
        code_style = ParagraphStyle(
            'DocCode', parent=styles['Normal'],
            fontName='Courier', fontSize=8.5, leading=11, textColor=colors.HexColor('#0f172a')
        )
        res_val_style = ParagraphStyle(
            'ResultVal', parent=styles['Normal'],
            fontName='Helvetica-Bold', fontSize=13, leading=16, alignment=TA_CENTER, textColor=colors.HexColor('#14532d')
        )

        story = []

        # --- Header ---
        header_table_data = [
            [
                Paragraph(f"<b>{r['app_name']}</b>", title_style),
                Paragraph(f"<b>Date:</b> {r['date']}<br/><b>Time:</b> {r['time']}<br/><b>Version:</b> {r['app_version']}", meta_style)
            ],
            [
                Paragraph(f"<b>Operation:</b> {r['operation']}", sub_style),
                Paragraph("", meta_style)
            ]
        ]
        header_table = Table(header_table_data, colWidths=[360, 180])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ]))
        story.append(header_table)
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#16a34a'), spaceAfter=10, spaceBefore=4))

        # --- Section 1: Input Data ---
        story.append(Paragraph("1. INPUT DATA", sec_style))
        q = r['input']
        input_lines = []
        if q.get('operation'): input_lines.append(f"<b>Operation:</b> {q['operation']}")
        if q.get('matrix_a'): input_lines.append(f"<b>Matrix A:</b> {q['matrix_a']}")
        if q.get('matrix_b'): input_lines.append(f"<b>Matrix B:</b> {q['matrix_b']}")
        if q.get('matrix'): input_lines.append(f"<b>Input Matrix:</b> {q['matrix']}")
        if q.get('scalar') is not None: input_lines.append(f"<b>Scalar k:</b> {q['scalar']}")
        if q.get('vector_u') or q.get('vector_a'): input_lines.append(f"<b>Vector u:</b> {q.get('vector_u') or q.get('vector_a')}")
        if q.get('vector_v') or q.get('vector_b'): input_lines.append(f"<b>Vector v:</b> {q.get('vector_v') or q.get('vector_b')}")
        if q.get('coefficients'): input_lines.append(f"<b>Coefficients [A]:</b> {q['coefficients']}")
        if q.get('constants'): input_lines.append(f"<b>Constants [b]:</b> {q['constants']}")

        q_html = "<br/>".join(input_lines) if input_lines else "Input parameters recorded."
        inp_table = Table([[Paragraph(q_html, body_style)]], colWidths=[540])
        inp_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f0f9ff')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#bae6fd')),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(inp_table)
        story.append(Spacer(1, 8))

        # --- Section 2: Mathematical Theory ---
        story.append(Paragraph("2. MATHEMATICAL THEORY", sec_style))
        story.append(Paragraph(r['theory'], body_style))
        story.append(Spacer(1, 8))

        # --- Section 3: Formula Used ---
        story.append(Paragraph("3. FORMULA USED", sec_style))
        f_html = f"<b>Plain Text:</b> {r['formula_plain']}<br/><b>LaTeX Formula:</b> <code>{r['formula_latex']}</code>"
        f_table = Table([[Paragraph(f_html, code_style)]], colWidths=[540])
        f_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(f_table)
        story.append(Spacer(1, 8))

        # --- Section 4: Step-by-Step Solution ---
        story.append(Paragraph("4. STEP-BY-STEP SOLUTION", sec_style))
        if r['steps']:
            for st in r['steps']:
                st_block = f"<b>Step {st['step_num']}: {st['title']}</b>"
                if st['text']: st_block += f"<br/>{st['text']}"
                if st['list']: st_block += "<br/>• " + "<br/>• ".join(st['list'])
                if st['latex']: st_block += f"<br/><font color='#1e40af'><code>{st['latex']}</code></font>"

                st_table = Table([[Paragraph(st_block, body_style)]], colWidths=[540])
                st_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
                    ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
                    ('LINELEFT', (0,0), (0,0), 3, colors.HexColor('#16a34a')),
                    ('PADDING', (0,0), (-1,-1), 6),
                ]))
                story.append(st_table)
                story.append(Spacer(1, 4))
        else:
            story.append(Paragraph("No detailed steps recorded.", body_style))
        story.append(Spacer(1, 6))

        # --- Section 5: Final Answer ---
        story.append(Paragraph("5. FINAL ANSWER", sec_style))
        fa = r['final_answer']
        fa_text = f"<b>Result:</b> {fa['display']}"
        if fa.get('latex'): fa_text += f"<br/><font color='#1e40af'>LaTeX: <code>{fa['latex']}</code></font>"

        fa_table = Table([[Paragraph(fa_text, res_val_style)]], colWidths=[540])
        fa_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f0fdf4')),
            ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor('#86efac')),
            ('PADDING', (0,0), (-1,-1), 10),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ]))
        story.append(fa_table)
        story.append(Spacer(1, 8))

        # --- Section 6: Verification ---
        story.append(Paragraph("6. VERIFICATION", sec_style))
        v = r['verification']
        v_text = (f"<b>Method:</b> {v['method']}<br/>"
                  f"<b>Status:</b> <font color='#15803d'><b>{v['status']}</b></font><br/>"
                  f"<b>Residual:</b> {v['residual']}<br/>"
                  f"<b>Details:</b> {v['details']}")
        v_table = Table([[Paragraph(v_text, body_style)]], colWidths=[540])
        v_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f0fdf4')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#bbf7d0')),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(v_table)

        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()


# ==============================================================================
# 2. WordExporter (python-docx)
# ==============================================================================
class WordExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        doc = Document()

        # Set Margins
        for section in doc.sections:
            section.top_margin = Inches(0.75)
            section.bottom_margin = Inches(0.75)
            section.left_margin = Inches(0.75)
            section.right_margin = Inches(0.75)

        # Title
        p_title = doc.add_paragraph()
        run_title = p_title.add_run(r['app_name'])
        run_title.font.name = 'Calibri'
        run_title.font.size = Pt(22)
        run_title.font.bold = True
        run_title.font.color.rgb = RGBColor(22, 163, 74)

        p_sub = doc.add_paragraph()
        p_sub.add_run(f"Operation: {r['operation']}\nDate: {r['date']}  |  Time: {r['time']}  |  Version: {r['app_version']}")
        p_sub.runs[0].font.size = Pt(10)
        p_sub.runs[0].font.color.rgb = RGBColor(100, 116, 139)

        doc.add_heading('1. Input Data', level=2)
        p_inp = doc.add_paragraph()
        q = r['input']
        inp_str = ""
        if q.get('matrix_a'): inp_str += f"Matrix A: {q['matrix_a']}\n"
        if q.get('matrix_b'): inp_str += f"Matrix B: {q['matrix_b']}\n"
        if q.get('matrix'): inp_str += f"Input Matrix: {q['matrix']}\n"
        if q.get('coefficients'): inp_str += f"Coefficients [A]: {q['coefficients']}\nConstants [b]: {q.get('constants')}\n"
        p_inp.add_run(inp_str if inp_str else "Input parameters provided.")

        doc.add_heading('2. Mathematical Theory', level=2)
        doc.add_paragraph(r['theory'])

        doc.add_heading('3. Formula Used', level=2)
        p_f = doc.add_paragraph()
        p_f.add_run(f"Plain Text Formula:\n{r['formula_plain']}\n\nLaTeX Formula:\n{r['formula_latex']}")

        doc.add_heading('4. Step-by-Step Solution', level=2)
        if r['steps']:
            for st in r['steps']:
                p_st = doc.add_paragraph()
                r_num = p_st.add_run(f"Step {st['step_num']}: {st['title']}\n")
                r_num.bold = True
                if st['text']: p_st.add_run(f"{st['text']}\n")
                for item in st['list']:
                    doc.add_paragraph(f"• {item}", style='List Bullet')
                if st['latex']:
                    p_code = doc.add_paragraph()
                    r_c = p_code.add_run(st['latex'])
                    r_c.font.name = 'Courier New'
                    r_c.font.size = Pt(9.5)
        else:
            doc.add_paragraph("No detailed steps recorded.")

        doc.add_heading('5. Final Answer', level=2)
        fa = r['final_answer']
        p_fa = doc.add_paragraph()
        r_fa = p_fa.add_run(f"FINAL RESULT: {fa['display']}")
        r_fa.bold = True
        r_fa.font.size = Pt(13)
        r_fa.font.color.rgb = RGBColor(20, 83, 45)

        doc.add_heading('6. Verification', level=2)
        v = r['verification']
        p_v = doc.add_paragraph()
        p_v.add_run(f"Method: {v['method']}\nStatus: {v['status']}\nResidual: {v['residual']}\nDetails: {v['details']}")

        # Footer
        section = doc.sections[0]
        footer = section.footer
        p_ftr = footer.paragraphs[0]
        p_ftr.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        p_ftr.text = f"Linear Algebra Solver {r['app_version']} — Page 1"

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()


# ==============================================================================
# 3. ExcelExporter (openpyxl)
# ==============================================================================
class ExcelExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        wb = openpyxl.Workbook()

        # Styles
        hdr_fill = PatternFill(start_color="16A34A", end_color="16A34A", fill_type="solid")
        hdr_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        sec_font = Font(name="Calibri", size=12, bold=True, color="0F172A")
        bold_font = Font(name="Calibri", size=11, bold=True)
        thin_border = Border(
            left=Side(style='thin', color='CBD5E1'),
            right=Side(style='thin', color='CBD5E1'),
            top=Side(style='thin', color='CBD5E1'),
            bottom=Side(style='thin', color='CBD5E1')
        )

        # Worksheet 1: Summary
        ws1 = wb.active
        ws1.title = "Summary"
        ws1.append([r['app_name'], "Report Summary"])
        ws1.append(["Operation", r['operation']])
        ws1.append(["Date", r['date']])
        ws1.append(["Time", r['time']])
        ws1.append(["Version", r['app_version']])
        ws1.append([])
        ws1.append(["Mathematical Theory", r['theory']])
        ws1.append(["Formula Used", r['formula_plain']])
        ws1.append(["Final Answer", r['final_answer']['display']])
        ws1.append(["Verification Status", r['verification']['status']])

        # Worksheet 2: Input Matrix
        ws2 = wb.create_sheet(title="Input Matrix")
        ws2.append(["Parameter", "Value"])
        ws2.cell(row=1, column=1).fill = hdr_fill
        ws2.cell(row=1, column=1).font = hdr_font
        ws2.cell(row=1, column=2).fill = hdr_fill
        ws2.cell(row=1, column=2).font = hdr_font

        q = r['input']
        for key, val in q.items():
            ws2.append([str(key), str(val)])

        # Worksheet 3: Step-by-Step Solution
        ws3 = wb.create_sheet(title="Step-by-Step Solution")
        ws3.append(["Step #", "Title", "Explanation", "LaTeX / Formula"])
        for col in range(1, 5):
            ws3.cell(row=1, column=col).fill = hdr_fill
            ws3.cell(row=1, column=col).font = hdr_font

        for st in r['steps']:
            ws3.append([st['step_num'], st['title'], st['text'], st['latex']])

        # Worksheet 4: Final Answer
        ws4 = wb.create_sheet(title="Final Answer")
        ws4.append(["Property", "Value"])
        ws4.cell(row=1, column=1).fill = hdr_fill
        ws4.cell(row=1, column=1).font = hdr_font
        ws4.cell(row=1, column=2).fill = hdr_fill
        ws4.cell(row=1, column=2).font = hdr_font

        fa = r['final_answer']
        ws4.append(["Type", fa['type']])
        ws4.append(["Display Result", fa['display']])
        if fa.get('latex'): ws4.append(["LaTeX Result", fa['latex']])

        # Worksheet 5: Verification
        ws5 = wb.create_sheet(title="Verification")
        ws5.append(["Metric", "Value"])
        ws5.cell(row=1, column=1).fill = hdr_fill
        ws5.cell(row=1, column=1).font = hdr_font
        ws5.cell(row=1, column=2).fill = hdr_fill
        ws5.cell(row=1, column=2).font = hdr_font

        v = r['verification']
        ws5.append(["Method", v['method']])
        ws5.append(["Status", v['status']])
        ws5.append(["Residual", v['residual']])
        ws5.append(["Details", v['details']])

        # Auto-size columns across all sheets
        for sheet in wb.worksheets:
            for col in sheet.columns:
                max_len = max(len(str(cell.value or '')) for cell in col)
                col_letter = get_column_letter(col[0].column)
                sheet.column_dimensions[col_letter].width = max(max_len + 3, 12)

        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()


# ==============================================================================
# 4. CSVExporter
# ==============================================================================
class CSVExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        lines = []

        def esc(val):
            s = str(val or '').replace('"', '""')
            return f'"{s}"'

        lines.append(f"{esc('HEADER')},{esc(r['app_name'])},{esc(r['app_version'])}")
        lines.append(f"{esc('OPERATION')},{esc(r['operation'])}")
        lines.append(f"{esc('TIMESTAMP')},{esc(r['date'] + ' ' + r['time'])}")
        lines.append("")

        lines.append(f"{esc('INPUT_DATA')}")
        for k, v in r['input'].items():
            lines.append(f"{esc(k)},{esc(v)}")
        lines.append("")

        lines.append(f"{esc('THEORY')},{esc(r['theory'])}")
        lines.append(f"{esc('FORMULA_PLAIN')},{esc(r['formula_plain'])}")
        lines.append(f"{esc('FORMULA_LATEX')},{esc(r['formula_latex'])}")
        lines.append("")

        lines.append(f"{esc('STEP_NUM')},{esc('TITLE')},{esc('EXPLANATION')},{esc('LATEX')}")
        for st in r['steps']:
            lines.append(f"{esc(st['step_num'])},{esc(st['title'])},{esc(st['text'])},{esc(st['latex'])}")
        lines.append("")

        lines.append(f"{esc('FINAL_ANSWER')},{esc(r['final_answer']['display'])}")
        lines.append(f"{esc('VERIFICATION_STATUS')},{esc(r['verification']['status'])}")
        lines.append(f"{esc('VERIFICATION_RESIDUAL')},{esc(r['verification']['residual'])}")

        return "\n".join(lines)


# ==============================================================================
# 5. JSONExporter
# ==============================================================================
class JSONExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        payload = {
            "application": r['app_name'],
            "version": r['app_version'],
            "operation": r['operation'],
            "date": r['date'],
            "time": r['time'],
            "timestamp": r['timestamp'],
            "input": r['input'],
            "theory": r['theory'],
            "formula": r['formula_plain'],
            "formula_latex": r['formula_latex'],
            "steps": r['steps'],
            "final_answer": r['final_answer'],
            "verification": r['verification']
        }
        return json.dumps(payload, indent=2)


# ==============================================================================
# 6. MarkdownExporter
# ==============================================================================
class MarkdownExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        md = []

        md.append(f"# {r['app_name']}")
        md.append(f"**Operation:** {r['operation']}  ")
        md.append(f"**Generated:** {r['date']} at {r['time']} | **Version:** {r['app_version']}  \n")
        md.append("---")

        md.append("## 1. Input Data")
        if r['input']:
            for k, v in r['input'].items():
                md.append(f"- **{k}:** `{v}`")
        else:
            md.append("*No specific input data captured.*")
        md.append("")

        md.append("## 2. Mathematical Theory")
        md.append(f"> {r['theory']}\n")

        md.append("## 3. Formula Used")
        md.append(f"**Plain Text:** `{r['formula_plain']}`  ")
        md.append(f"$$\n{r['formula_latex']}\n$$\n")

        md.append("## 4. Step-by-Step Solution")
        if r['steps']:
            for st in r['steps']:
                md.append(f"### Step {st['step_num']}: {st['title']}")
                if st['text']: md.append(f"{st['text']}\n")
                for item in st['list']: md.append(f"- {item}")
                if st['latex']: md.append(f"\n$$\n{st['latex']}\n$$\n")
        else:
            md.append("*No detailed solution steps recorded.*\n")

        md.append("## 5. Final Answer")
        md.append(f"**Result:** `{r['final_answer']['display']}`  ")
        if r['final_answer'].get('latex'):
            md.append(f"$$\n{r['final_answer']['latex']}\n$$\n")

        md.append("## 6. Verification")
        v = r['verification']
        md.append(f"- **Method:** {v['method']}")
        md.append(f"- **Status:** `{v['status']}`")
        md.append(f"- **Residual:** `{v['residual']}`")
        md.append(f"- **Details:** {v['details']}\n")

        md.append("---")
        md.append(f"*Generated by {r['app_name']} {r['app_version']}*")

        return "\n".join(md)


# ==============================================================================
# 7. LatexExporter
# ==============================================================================
class LatexExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        tex = []

        tex.append(r"\documentclass[11pt,a4paper]{article}")
        tex.append(r"\usepackage[utf8]{inputenc}")
        tex.append(r"\usepackage{amsmath,amssymb,amsfonts}")
        tex.append(r"\usepackage{geometry}")
        tex.append(r"\geometry{margin=1in}")
        tex.append(r"\usepackage{xcolor}")
        tex.append(r"\usepackage{hyperref}")
        tex.append("")
        tex.append(r"\title{\textbf{" + r['app_name'] + r"}\\[0.5em]\large " + r['operation'] + r"}")
        tex.append(r"\author{Linear Algebra Engine " + r['app_version'] + r"}")
        tex.append(r"\date{" + r['date'] + r" " + r['time'] + r"}")
        tex.append("")
        tex.append(r"\begin{document}")
        tex.append(r"\maketitle")
        tex.append("")

        tex.append(r"\section*{1. Input Data}")
        tex.append(r"\begin{itemize}")
        for k, v in r['input'].items():
            k_esc = str(k).replace('_', r'\_')
            v_esc = str(v).replace('_', r'\_')
            tex.append(r"\item \textbf{" + k_esc + r":} " + v_esc)
        tex.append(r"\end{itemize}")
        tex.append("")

        tex.append(r"\section*{2. Mathematical Theory}")
        tex.append(r['theory'].replace('%', r'\%'))
        tex.append("")

        tex.append(r"\section*{3. Formula Used}")
        tex.append(r"\[ " + r['formula_latex'] + r" \]")
        tex.append("")

        tex.append(r"\section*{4. Step-by-Step Solution}")
        for st in r['steps']:
            t_esc = str(st['title']).replace('_', r'\_')
            tex.append(r"\subsection*{Step " + str(st['step_num']) + r": " + t_esc + r"}")
            if st['text']: tex.append(str(st['text']).replace('%', r'\%') + r"\\[0.5em]")
            if st['latex']: tex.append(r"\[ " + st['latex'] + r" \]")
        tex.append("")

        tex.append(r"\section*{5. Final Answer}")
        disp_esc = str(r['final_answer']['display']).replace('_', r'\_')
        tex.append(r"\textbf{Result:} " + disp_esc)
        if r['final_answer'].get('latex'):
            tex.append(r"\[ " + r['final_answer']['latex'] + r" \]")
        tex.append("")

        tex.append(r"\section*{6. Verification}")
        v = r['verification']
        tex.append(r"\begin{itemize}")
        tex.append(r"\item \textbf{Method:} " + str(v['method']))
        tex.append(r"\item \textbf{Status:} " + str(v['status']))
        tex.append(r"\item \textbf{Residual:} " + str(v['residual']))
        tex.append(r"\item \textbf{Details:} " + str(v['details']))
        tex.append(r"\end{itemize}")
        tex.append("")

        tex.append(r"\end{document}")
        return "\n".join(tex)


# ==============================================================================
# 8. HTMLExporter
# ==============================================================================
class HTMLExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)

        css = """
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; font-size: 14px; color: #1e293b; background: #f8fafc; padding: 30px; }
        .container { max-width: 900px; margin: 0 auto; background: #fff; border: 1px solid #e2e8f0; border-radius: 12px; padding: 36px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
        .hdr { border-bottom: 3px solid #16a34a; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
        .title { font-size: 24px; font-weight: 800; color: #16a34a; }
        .subtitle { font-size: 14px; font-weight: 600; color: #334155; }
        .meta { text-align: right; font-size: 11px; color: #64748b; }
        .section-title { font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: .08em; color: #0891b2; margin: 20px 0 8px; }
        .card { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px; padding: 14px 18px; margin-bottom: 16px; }
        .step-card { background: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #16a34a; border-radius: 6px; padding: 12px 16px; margin-bottom: 10px; }
        .res-card { background: #f0fdf4; border: 2px solid #86efac; border-radius: 10px; padding: 18px; text-align: center; margin-bottom: 20px; }
        .res-val { font-size: 20px; font-weight: 800; color: #14532d; }
        .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 12px; text-align: center; color: #94a3b8; font-size: 11px; }
        @media print { body { background: #fff; padding: 0; } .container { border: none; box-shadow: none; } }
        """

        steps_html = ""
        if r['steps']:
            for st in r['steps']:
                steps_html += f"""
                <div class="step-card">
                    <div style="font-weight:700;color:#0f172a;">Step {st['step_num']}: {st['title']}</div>
                    {f'<div style="color:#475569;margin-top:4px;">{st["text"]}</div>' if st['text'] else ''}
                    {f'<div style="margin-top:6px;font-family:monospace;color:#1e40af;">\\[ {st["latex"]} \\]</div>' if st['latex'] else ''}
                </div>"""
        else:
            steps_html = "<p style='color:#94a3b8;'>No detailed steps recorded.</p>"

        q_html = "".join([f"<div><b>{k}:</b> {v}</div>" for k, v in r['input'].items()])

        html = f"""<!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{r['app_name']} — {r['operation']}</title>
            <style>{css}</style>
            <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" async></script>
        </head>
        <body>
            <div class="container">
                <div class="hdr">
                    <div>
                        <div class="title">{r['app_name']}</div>
                        <div class="subtitle">{r['operation']}</div>
                    </div>
                    <div class="meta">
                        Date: {r['date']}<br>Time: {r['time']}<br>Version: {r['app_version']}
                    </div>
                </div>

                <div class="section-title">1. Input Data</div>
                <div class="card">{q_html if q_html else 'Input parameters provided.'}</div>

                <div class="section-title">2. Mathematical Theory</div>
                <p>{r['theory']}</p>

                <div class="section-title">3. Formula Used</div>
                <div class="card">
                    <div><b>Plain:</b> {r['formula_plain']}</div>
                    <div style="margin-top:8px;">\\[ {r['formula_latex']} \\]</div>
                </div>

                <div class="section-title">4. Step-by-Step Solution</div>
                {steps_html}

                <div class="section-title">5. Final Answer</div>
                <div class="res-card">
                    <div class="res-val">{r['final_answer']['display']}</div>
                    {f'<div style="margin-top:8px;">\\[ {r["final_answer"]["latex"]} \\]</div>' if r['final_answer'].get('latex') else ''}
                </div>

                <div class="section-title">6. Verification</div>
                <div class="card" style="background:#f0fdf4;border-color:#bbf7d0;">
                    <div><b>Method:</b> {r['verification']['method']}</div>
                    <div><b>Status:</b> <span style="color:#15803d;font-weight:700;">{r['verification']['status']}</span></div>
                    <div><b>Residual:</b> {r['verification']['residual']}</div>
                    <div><b>Details:</b> {r['verification']['details']}</div>
                </div>

                <div class="footer">
                    Generated by {r['app_name']} {r['app_version']} | {r['date']} {r['time']}
                </div>
            </div>
        </body>
        </html>"""

        return html


# ==============================================================================
# 9. TextExporter
# ==============================================================================
class TextExporter(BaseExporter):

    @classmethod
    def export(cls, solution_data, module_name, question_data=None):
        r = cls.normalize_report_data(solution_data, module_name, question_data)
        W = 68
        hr = "=" * W
        hr2 = "-" * W

        t = []
        t.append(hr)
        t.append(r['app_name'].center(W))
        t.append(f"Detailed Solution Report — {r['app_version']}".center(W))
        t.append(hr)
        t.append(f"  Operation : {r['operation']}")
        t.append(f"  Date      : {r['date']}  |  Time: {r['time']}")
        t.append(hr)
        t.append("")

        t.append("  [1] INPUT DATA")
        t.append(f"  {hr2}")
        for k, v in r['input'].items():
            t.append(f"  • {k}: {v}")
        t.append("")

        t.append("  [2] MATHEMATICAL THEORY")
        t.append(f"  {hr2}")
        t.append(f"  {r['theory']}")
        t.append("")

        t.append("  [3] FORMULA USED")
        t.append(f"  {hr2}")
        t.append(f"  Formula: {r['formula_plain']}")
        t.append(f"  LaTeX  : {r['formula_latex']}")
        t.append("")

        t.append("  [4] STEP-BY-STEP SOLUTION")
        t.append(f"  {hr2}")
        if r['steps']:
            for st in r['steps']:
                t.append(f"\n  Step {st['step_num']}: {st['title']}")
                if st['text']: t.append(f"    {st['text']}")
                for item in st['list']: t.append(f"    ▸ {item}")
                if st['latex']: t.append(f"    LaTeX: {st['latex']}")
        else:
            t.append("  (No detailed steps recorded)")
        t.append("")

        t.append("  [5] FINAL ANSWER")
        t.append(f"  {hr2}")
        t.append(f"  RESULT: {r['final_answer']['display']}")
        if r['final_answer'].get('latex'):
            t.append(f"  LaTeX : {r['final_answer']['latex']}")
        t.append("")

        t.append("  [6] VERIFICATION")
        t.append(f"  {hr2}")
        v = r['verification']
        t.append(f"  Method  : {v['method']}")
        t.append(f"  Status  : {v['status']}")
        t.append(f"  Residual: {v['residual']}")
        t.append(f"  Details : {v['details']}")
        t.append("")

        t.append(hr)
        t.append(f"  {r['app_name']} {r['app_version']} | {r['date']} {r['time']}")
        t.append(hr)

        return "\n".join(t)


# ==============================================================================
# ExportService Manager / Factory Class
# ==============================================================================
class ExportService:

    EXPORTERS = {
        'pdf': (PDFExporter, 'application/pdf', '.pdf'),
        'docx': (WordExporter, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.docx'),
        'word': (WordExporter, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.docx'),
        'xlsx': (ExcelExporter, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '.xlsx'),
        'excel': (ExcelExporter, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '.xlsx'),
        'csv': (CSVExporter, 'text/csv', '.csv'),
        'json': (JSONExporter, 'application/json', '.json'),
        'md': (MarkdownExporter, 'text/markdown', '.md'),
        'markdown': (MarkdownExporter, 'text/markdown', '.md'),
        'tex': (LatexExporter, 'application/x-tex', '.tex'),
        'latex': (LatexExporter, 'application/x-tex', '.tex'),
        'html': (HTMLExporter, 'text/html', '.html'),
        'txt': (TextExporter, 'text/plain', '.txt'),
        'text': (TextExporter, 'text/plain', '.txt')
    }

    @classmethod
    def export(cls, fmt, solution_data, module_name, question_data=None):
        """
        Generate exported content based on format.
        Returns tuple: (file_bytes_or_str, mimetype, filename)
        """
        fmt_key = str(fmt or 'pdf').lower().strip()
        if fmt_key not in cls.EXPORTERS:
            fmt_key = 'pdf'

        exporter_cls, mimetype, ext = cls.EXPORTERS[fmt_key]

        safe_mod = (module_name or 'solution').lower().replace(' ', '_')
        safe_mod = re.sub(r'[^a-z0-9_]', '', safe_mod)
        filename = f"{safe_mod}_report{ext}"

        content = exporter_cls.export(solution_data, module_name, question_data)
        return content, mimetype, filename
